I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "game/screens.rpy", line 251, in <module>
    spacing gui.second_spacing
AttributeError: 'StoreModule' object has no attribute 'second_spacing'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/main.py", line 635, in main
    run(restart)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/main.py", line 75, in run
    renpy.translation.init_translation()
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/translation/__init__.py", line 664, in init_translation
    renpy.store._init_language() # type: ignore
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/translation/__init__.py", line 758, in change_language
    new_change_language(tl, language)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/translation/__init__.py", line 710, in new_change_language
    i.apply()
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/ast.py", line 2784, in apply
    value = renpy.python.py_eval(expr)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens.rpy", line 251, in <module>
    spacing gui.second_spacing
AttributeError: 'StoreModule' object has no attribute 'second_spacing'

macOS-14.4.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
ep4 1.0
Mon Apr  8 02:53:45 2024
