I'm sorry, but an uncaught exception occurred.

While running game code:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jodongsu/Desktop/미연시/ep4/game/saves/persistent.1712425076.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/main.py", line 649, in main
    renpy.persistent.update(True)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/persistent.py", line 434, in update
    save()
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/persistent.py", line 455, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/savelocation.py", line 566, in save_persistent
    l.save_persistent(data)
  File "/Users/jodongsu/Documents/renpy-8.2.1-sdk/renpy/savelocation.py", line 374, in save_persistent
    with open(fn_tmp, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jodongsu/Desktop/미연시/ep4/game/saves/persistent.1712425076.tmp'

macOS-14.4.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
ep4 1.0
Sun Apr  7 12:43:16 2024
